services:
  www:
    # image: php:7.4-apache
    build: ./php
    container_name: www_docker_cours_ecommerce
    links:
      - mysql:mysql
    volumes:
      - "./:/var/www"
      - "./upload:/var/www/public/upload"
    ports:
      - "8090:80"
    networks:
      - cours_ecommerce

  mysql:
    image: mysql
    container_name: db_docker_cours_ecommerce
    #restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - cours_ecommerce

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_cours_ecommerce
    #restart: always
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    networks:
      - cours_ecommerce

networks:
  cours_ecommerce:


volumes:
  mysql:
